services:
  postgres:
    image: 'postgres:16-alpine'
    command: >
      postgres 
      -c max_connections=500
      -c shared_buffers=8GB
      -c work_mem=32MB
      -c maintenance_work_mem=2GB
      -c max_wal_size=8GB
      -c max_worker_processes=24
      -c max_parallel_workers=12
      -c max_parallel_workers_per_gather=6
      -c effective_cache_size=24GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=128MB
      -c random_page_cost=1.0
      -c effective_io_concurrency=200
      -c max_parallel_maintenance_workers=6
      -c checkpoint_timeout=15min
      -c bgwriter_lru_maxpages=1000
    restart: unless-stopped
    ports:
      - '6541:5432' # Use a port unlikely to be in use
    environment:
      - POSTGRES_DB=shuttle
      - POSTGRES_USER=shuttle
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'env', 'pg_isready', '--dbname', '$$POSTGRES_DB', '-U', '$$POSTGRES_USER' ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - shuttle-network

  redis:
    image: 'redis:7.2-alpine'
    restart: unless-stopped
    command: --save 1 1 --loglevel warning --maxmemory-policy noeviction
    volumes:
      - redis-data:/data
    ports:
      - '16379:6379'
    healthcheck:
      test: [ 'CMD-SHELL', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - shuttle-network

  # Optional: Add Grafana for monitoring your snapchain
  grafana:
    image: 'grafana/grafana:10.0.3'
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - shuttle-network

volumes:
  postgres-data:
  redis-data:
  grafana-data:

networks:
  shuttle-network: